name: HideAndSeek
main: io.github.Laplace.HideAndSeek.HideAndSeek
version: 0.0.1
author: Laplace, MaoWTM
commands:
   gamestart:
      description: Assign teams to logged-in players and start the Hide and seek game.
      usage: /gamestart
   setteam:
      description: Manually assign (or change) team of a player.
      usage: /setteam <player> <team>
   listteams:
      description: List which players are in what team.
      usage: /listteams <team|all>
