name: HideAndSeek
main: io.github.Laplace.HideAndSeek.HideAndSeek
version: 0.0.1
author: Laplace, MaoWTM
commands:
   startgame:
      description: Assign teams to logged-in players and start the Hide and seek game.
      usage: /startgame
   setteam:
      description: Manually assign (or change) team of a player.
      usage: /setteam <player> <team>
   listteams:
      description: List which players are in what team.
      usage: /listteams <team|all>
   endgame:
      description: Reset the game
      usage: /endgame
   adjustmaxhealth:
      description: Adjust max health of team
      usage: /adjustmaxhealth <team> <offset>
   hspos1:
      description: Mark current player position as first corner of hide-and-seek area
      usage: /hspos1
   hspos2:
      description: Mark current player position as second corner of hide-and-seek area
      usage: /hspos2
